import { colorTheme } from "@/constants/Colors";

type Palette = typeof colorTheme.catppuccin.latte;

export const getListTheme = (palette: Palette, isDark: boolean) => ({
  colors: {
    card: isDark ? palette.surface0 : "#ffffff",
    row: isDark ? palette.surface1 : palette.mantle,
    divider: isDark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.08)",
    subtleText: palette.subtext0,
    secondaryText: palette.subtext1,
    emptyText: palette.subtext0,
    text: palette.text,
    iconButton: isDark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.05)",
  },
  spacing: {
    containerPadding: 12,
    sectionGap: 16,
    sectionPadding: 12,
    headerHorizontal: 6,
    headerVertical: 4,
    rowHorizontal: 6,
    rowVertical: 12,
    iconGap: 12,
  },
  radii: {
    section: 18,
    inner: 12,
    iconButton: 18,
  },
  sizes: {
    iconButton: 36,
  },
  typography: {
    sectionTitleSize: 18,
    sectionTitleWeight: "700",
    sectionPercentSize: 16,
    sectionPercentWeight: "700",
    sectionTotalsSize: 15,
    sectionTotalsWeight: "700",
    rowTitleSize: 16,
    rowTitleWeight: "700",
    rowSubSize: 13,
    rowTimeSize: 15,
    rowTimeWeight: "700",
    taskGoalSize: 14,
    taskGoalWeight: "600",
    rowPercentSize: 12,
    emptySize: 16,
  },
  shadow: {
    shadowOpacity: isDark ? 0.2 : 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  layout: {
    settings: {
      scrollPaddingVertical: 16,
      scrollGap: 18,
      sectionGap: 10,
      cardRadius: 22,
      cardPaddingVertical: 12,
      cardPaddingHorizontal: 12,
      cardGap: 6,
      sectionTitleSize: 17,
      sectionTitleWeight: "700",
      subsectionTitleSize: 13,
      subsectionTitleWeight: "700",
      subsectionLetterSpacing: 0.2,
      subsectionPaddingHorizontal: 6,
      rowPaddingVertical: 8,
      rowPaddingHorizontal: 6,
      rowGap: 12,
      rowLeftGap: 10,
      rowRightGap: 8,
      rowLabelSize: 15,
      rowLabelWeight: "600",
      rowValueSize: 13,
      rowValueWeight: "600",
      dividerMarginHorizontal: 6,
      groupDividerMarginVertical: 6,
      iconBadgeSize: 30,
      iconBadgeRadius: 12,
      accentPreviewSize: 20,
      accentPreviewRadius: 10,
    },
    select: {
      scrollPaddingVertical: 16,
      scrollPaddingBottom: 20,
      cardRadius: 22,
      cardPaddingVertical: 12,
      cardPaddingHorizontal: 12,
      rowPaddingVertical: 10,
      rowPaddingHorizontal: 6,
      rowGap: 12,
      rowLeftGap: 12,
      rowLabelSize: 15,
      rowLabelWeight: "600",
      swatchSize: 22,
      swatchRadius: 11,
      swatchBorderWidth: 2,
    },
    sheet: {
      containerPadding: 15,
      headerMarginBottom: 15,
      titleSize: 18,
      titleWeight: "700",
      topRadius: 24,
      popupRadius: 26,
      popupMargin: 12,
      popupMaxWidth: 520,
      headerButtonSize: 46,
      headerButtonRadius: 23,
      subMenuMarginTop: 10,
      subMenuMarginBottom: 10,
      subMenuRadius: 10,
      subMenuPaddingHorizontal: 18,
      subMenuPaddingVertical: 10,
      subMenuTextPaddingLeft: 10,
      subMenuTextEndPaddingRight: 8,
      menuTextSize: 16,
      menuTextWeight: "500",
      menuTextSecondaryWeight: "300",
      textInputSize: 18,
      textInputWeight: "500",
      paletteSwatchSize: 34,
      paletteSwatchRadius: 12,
    },
  },
});
